name: 'Firebase Deployment'
author: 'Scheduling Workbox System <sws2apps.notification@gmail.com>'
description: 'A GitHub Action to deploy to Firebase'
inputs:
  workloadIdentityProvider:
    description: 'The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name. This must be the full identifier which includes all parts'
    required: true
  serviceAccount:
    description: 'Email address or unique identifier of the Google Cloud service account for which to generate credentials'
    required: true
  project:
    description: 'Name of the firebase project you will deploy the site'
    required: true
  config:
    description: 'Path to the firebase.json config file'
    required: false
  function:
    description: 'Deploy only firebase functions'
    required: false
  hosting:
    description: 'Deploy only hosting site'
    required: false
  node-version:
    description: 'NodeJS Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    required: false
    default: 'current'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      shell: bash

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ inputs.workloadIdentityProvider }}
        service_account: ${{ inputs.serviceAccount }}

    - name: Run Deployment
      env:
        project: ${{ inputs.project }}
        config: ${{ inputs.config }}
        function: ${{ inputs.function }}
        hosting: ${{ inputs.hosting }}
      run: node ${{github.action_path}}/dist/index.js
      shell: bash

branding:
  icon: 'upload-cloud'
  color: 'purple'
