name: Dependency Review

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for dependency review
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Running Dependency Review
        uses: actions/dependency-review-action@e58c696e52cac8e62d61cc21fda89565d71505d7
