name: CD

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish_marketplace:
    name: Publish Action to Marketplace
    if: ${{ github.repository == 'sws2apps/firebase-deployment' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js current version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: lts/Krypton

      - name: Install package dependencies
        run: npm ci

      - name: Run Semantic Release to version and publish the action
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
